export const FETCH_NOTEBOOK_LIST_REQUEST = "FETCH_NOTEBOOK_LIST_REQUEST";
export const FETCH_NOTEBOOK_LIST_SUCCESS = "FETCH_NOTEBOOK_LIST_SUCCESS";
export const FETCH_NOTEBOOK_LIST_FAILURE = "FETCH_NOTEBOOK_LIST_FAILURE";

export const TOGGLE_NOTEBOOK_PIN_REQUEST = "TOGGLE_NOTEBOOK_PIN_REQUEST";
export const TOGGLE_NOTEBOOK_PIN_SUCCESS = "TOGGLE_NOTEBOOK_PIN_SUCCESS";
export const TOGGLE_NOTEBOOK_PIN_FAILURE = "TOGGLE_NOTEBOOK_PIN_FAILURE";

export const TOGGLE_NOTEBOOK_ARCHIVE_REQUEST =
  "TOGGLE_NOTEBOOK_ARCHIVE_REQUEST";
export const TOGGLE_NOTEBOOK_ARCHIVE_SUCCESS =
  "TOGGLE_NOTEBOOK_ARCHIVE_SUCCESS";
export const TOGGLE_NOTEBOOK_ARCHIVE_FAILURE =
  "TOGGLE_NOTEBOOK_ARCHIVE_FAILURE";

export const NOTEBOOK_DELETE_REQUEST = "NOTEBOOK_DELETE_REQUEST";
export const NOTEBOOK_DELETE_SUCCESS = "NOTEBOOK_DELETE_SUCCESS";
export const NOTEBOOK_DELETE_FAILURE = "NOTEBOOK_DELETE_FAILURE";

export const NOTEBOOK_CHANGE_HEADERNAME_REQUEST =
  "NOTEBOOK_CHANGE_HEADERNAME_REQUEST";
export const NOTEBOOK_CHANGE_HEADERNAME_SUCCESS =
  "NOTEBOOK_CHANGE_HEADERNAME_SUCCESS";
export const NOTEBOOK_CHANGE_HEADERNAME_FAILURE =
  "NOTEBOOK_CHANGE_HEADERNAME_FAILURE";

// User model
export interface NotebookList {
  user_id: string;
  chat_id: string;
  is_archieved: number;
  is_pin: number;
  chat_header: string;
  timestamp: string;
}
